---
title: "Test-1-af-quarto"
author: "MZS"
format: html
---

## Keep it simple, stupid (R)

```{r}
1 + 1
```

## Setup Chunkus

```{r setup}
#| message: false
library(tidyverse)
post_meal_data <- read_csv2(
  here::here("data/post-meal-insulin.csv")
)
```

## About Me

- Dude: Michael
- Place: SDCC
- Stuff: Diabetes Research

I *like* **trains**

## Simple Code or not?

```{r}
3 * 3
```

## Testing for GIT
Should you git gut or gut git? You got to git it. Gut.

## Showing gut GIT data

```{r}
post_meal_data
```

```{r}
glimpse(post_meal_data)
```


```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-bmi-histo
#| message: false
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

@fig-bmi-histo

## New gut bar plot for Git

```{r}
#| message: false
#| fig-cap: "Group allocation count"
#| label: fig-group-bar
ggplot(post_meal_data, aes(x = Group)) +
  geom_bar()
```

See @fig-group-bar for allocation bar graph

## Fill?

```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = glykemi)) +
  geom_bar()
```

```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar()
```

```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```


## Plots side by side

```{r}
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```

```{r side-by-side-figs}
#| label: fig-bmi-group
#| fig-cap: "BMI and Group, side by side"
#| fig-subcap:
#|   - "Distribution of BMI."
#|   - "Group allocation."
#| layout-ncol: 2
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()

post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```
